# Generated by Django 3.0.3 on 2020-05-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='US',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoId', models.CharField(max_length=200)),
                ('numberOfTrendingDays', models.IntegerField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('channelTitle', models.CharField(max_length=200)),
                ('categoryId', models.IntegerField()),
                ('startViews', models.IntegerField()),
                ('endViews', models.IntegerField()),
                ('startLikes', models.IntegerField()),
                ('endLikes', models.IntegerField()),
                ('startDislikes', models.IntegerField()),
                ('endDislikes', models.IntegerField()),
                ('startCommentCount', models.IntegerField()),
                ('endCommentCount', models.IntegerField()),
                ('trendingRank', models.IntegerField()),
            ],
        ),
    ]
