# Generated by Django 3.0.3 on 2020-05-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='us',
            name='endDate',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='us',
            name='startDate',
            field=models.CharField(max_length=30),
        ),
    ]
