# Generated by Django 3.0.3 on 2020-05-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200521_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='India',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoId', models.CharField(max_length=200)),
                ('numberOfTrendingDays', models.IntegerField()),
                ('startDate', models.CharField(max_length=30)),
                ('endDate', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('channelTitle', models.CharField(max_length=200)),
                ('categoryId', models.IntegerField()),
                ('startViews', models.IntegerField()),
                ('endViews', models.IntegerField()),
                ('startLikes', models.IntegerField()),
                ('endLikes', models.IntegerField()),
                ('startDislikes', models.IntegerField()),
                ('endDislikes', models.IntegerField()),
                ('startCommentCount', models.IntegerField()),
                ('endCommentCount', models.IntegerField()),
                ('trendingRank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoId', models.CharField(max_length=200)),
                ('numberOfTrendingDays', models.IntegerField()),
                ('startDate', models.CharField(max_length=30)),
                ('endDate', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('channelTitle', models.CharField(max_length=200)),
                ('categoryId', models.IntegerField()),
                ('startViews', models.IntegerField()),
                ('endViews', models.IntegerField()),
                ('startLikes', models.IntegerField()),
                ('endLikes', models.IntegerField()),
                ('startDislikes', models.IntegerField()),
                ('endDislikes', models.IntegerField()),
                ('startCommentCount', models.IntegerField()),
                ('endCommentCount', models.IntegerField()),
                ('trendingRank', models.IntegerField()),
            ],
        ),
    ]
