# Generated by Django 3.0.7 on 2020-07-15 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_india_uk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='India',
        ),
        migrations.DeleteModel(
            name='UK',
        ),
        migrations.DeleteModel(
            name='US',
        ),
    ]
