from django.urls import path
from . import views
urlpatterns = [
    path('', views.splash, name='splash'),
    path('home/', views.home, name='youtube-home'),
    path('about/', views.about, name='youtube-about'),
    path('home/bubble-chart', views.home_bubble_chart, name='bubble-chart'),
    path('us/', views.us, name='youtube-us'),
    path('uk/', views.uk, name='youtube-uk'),
    path('india/', views.india, name='youtube-india'),
    path('reports/',views.report, name ='youtube-report' ),
    path('us/us-category-count-chart/', views.us_category_count_chart,
         name='us-category-count-chart'),
    path('uk/uk-category-count-chart/', views.britain_category_count_chart,
         name='uk-category-count-chart'),
    path('india/india-category-count-chart/', views.india_category_count_chart,
         name='india-category-count-chart'),
    path('us/us-category-graph-line/', views.us_category_graph_line,
         name='us-category-graph-line'),
     path('uk/uk-category-graph-line/', views.britain_category_graph_line,
         name='uk-category-graph-line'),
    path('india/india-category-graph-line/', views.india_category_graph_line,
         name='india-category-graph-line'),
    path('uk/uk-most-trending-channel/', views.britain_most_trending_channel,
         name='uk-most-trending-channel'),
     path('india/india-most-trending-channel/', views.india_most_trending_channel,
         name='india-most-trending-channel'),
     path('us/us-most-trending-channel/', views.us_most_trending_channel,
         name='us-most-trending-channel'),
     
]
